import product from '@/sanity/schemas/product';
import Head from 'next/head'
//import Image from 'next/image'
//import { Inter } from 'next/font/google'
//import styles from '@/styles/Home.module.css'
import { Product, FooterBanner, HeroBanner } from '../components';
import  {client}  from '../lib/client';

//const inter = Inter({ subsets: ['latin'] })

export default function Home({ products, bannerData }) {
  return (
    <>
      <Head>
        <title>Joy_Store App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <HeroBanner heroBanner={bannerData.length && bannerData[0]}/>
     
       
      <div className='products-heading'>
        <h2>Best Sellar Products</h2>
         <p>Speaker there are many variations passenges</p>
      </div>

       <div className='products-container'>
        {products?.map((product)=> <Product key={product._id} product={product} /> )}
          </div>
      
      <FooterBanner footerBanner={bannerData && bannerData[0]} />
      
       </main>
    </>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData }
  }
}